// Configuration file for admin interface
// Auto-generated by configure-endpoints script
// Generated on: 2025-10-29T22:04:12.409Z
// Environment: dev

export interface Config {
  environment: string;
  webSocketUrl: string;
  connectionType: 'user' | 'admin';
  reconnectInterval: number;
  maxReconnectAttempts: number;
  connectionTimeout: number;
  deploymentMode: string;
  enableLogging: boolean;
}

export const configManager = {
  getConfiguration: () => config,
  getConfig: () => config,
  refreshConfig: () => config,
  isConfigurationValid: () => true
};

export const config: Config = {
  environment: 'dev',
  webSocketUrl: 'wss://lpoon64z0m.execute-api.eu-central-1.amazonaws.com/prod',
  connectionType: 'admin',
  reconnectInterval: 5000,
  maxReconnectAttempts: 10,
  connectionTimeout: 30000,
  deploymentMode: 'aws',
  enableLogging: true
};
