apiVersion: messaging.example.com/v1alpha1
kind: UserAdminMessaging
metadata:
  name: user-admin-messaging-staging
  namespace: default
spec:
  environment: staging
  region: eu-central-1
  removalPolicy: Retain