apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: user-admin-messaging
  namespace: default
  labels:
    provider: aws
    service: messaging
spec:
  compositeTypeRef:
    apiVersion: clc.lockhead.cloud/v1alpha1
    kind: XUserAdminMessaging
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
        # DynamoDB Table for WebSocket connections
          - name: websocket-connections-table
            base:
              apiVersion: dynamodb.aws.m.upbound.io/v1beta1
              kind: Table
              spec:
                forProvider:
                  region: eu-central-1
                  billingMode: PAY_PER_REQUEST
                  attribute:
                    - name: connectionId
                      type: S
                    - name: connectionType
                      type: S
                  hashKey: connectionId
                  #rangeKey: connectionType               
                  globalSecondaryIndex:
                    - hashKey: connectionType
                      name: connectionType
                      projectionType: ALL
                  ttl:
                    attributeName: ttl
                    enabled: true
                  tags:
                    Environment: dev
                    Project: user-admin-messaging
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-websocket-connections-%s"
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.tags.Environment

          # IAM Role for Lambda functions
          - name: lambda-execution-role
            base:
              apiVersion: iam.aws.m.upbound.io/v1beta1
              kind: Role
              metadata:
                labels:
                  clc.lockhead.cloud/testing-aws-role: aws
              spec:
                forProvider:
                  assumeRolePolicy: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": "lambda.amazonaws.com"
                          },
                          "Action": "sts:AssumeRole"
                        }
                      ]
                    }
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-lambda-execution-role-%s"
                      type: Format

          # IAM Policy for DynamoDB access
          - name: dynamodb-policy
            base:
              apiVersion: iam.aws.m.upbound.io/v1beta1
              kind: Policy
              spec:
                forProvider:
                  policy: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Action": [
                            "dynamodb:GetItem",
                            "dynamodb:PutItem",
                            "dynamodb:UpdateItem",
                            "dynamodb:DeleteItem",
                            "dynamodb:Query",
                            "dynamodb:Scan"
                          ],
                          "Resource": "*"
                        }
                      ]
                    }
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-dynamodb-policy-%s"
                      type: Format

          # Connection Manager Lambda Function
          - name: connection-manager-function
            base:
              apiVersion: lambda.aws.m.upbound.io/v1beta1
              kind: Function
              spec:
                forProvider:
                  region: eu-central-1
                  runtime: nodejs22.x
                  handler: index.handler
                  s3Key: demo-lambda.zip
                  s3Bucket: clc.lockhead.cloud.demo
                  #code:
                  #  zipFile: |
                  #    exports.handler = async (event) => {
                  #      console.log('Connection event:', JSON.stringify(event, null, 2));
                  #      return { statusCode: 200 };
                  #    };
                  environment:
                    variables: {}
                  roleSelector:
                    matchLabels:
                      clc.lockhead.cloud/testing-aws-role: aws
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-connection-manager-%s"
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.environment.variables.CONNECTIONS_TABLE_NAME
                transforms:
                  - type: string
                    string:
                      fmt: "websocket-connections-%s"
                      type: Format

          # Message Handler Lambda Function
          - name: message-handler-function
            base:
              apiVersion: lambda.aws.m.upbound.io/v1beta1
              kind: Function
              spec:
                forProvider:
                  region: eu-central-1
                  runtime: nodejs22.x
                  handler: index.handler
                  s3Key: demo-lambda.zip
                  s3Bucket: clc.lockhead.cloud.demo
                  #code:
                  #  zipFile: |
                  #    exports.handler = async (event) => {
                  #      console.log('Message event:', JSON.stringify(event, null, 2));
                  #      return { statusCode: 200 };
                  #    };
                  environment:
                    variables: {}
                  roleSelector:
                    matchLabels:
                      clc.lockhead.cloud/testing-aws-role: aws
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-message-handler-%s"
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.environment.variables.CONNECTIONS_TABLE_NAME
                transforms:
                  - type: string
                    string:
                      fmt: "websocket-connections-%s"
                      type: Format

          # WebSocket API Gateway
          - name: websocket-api
            base:
              apiVersion: apigatewayv2.aws.m.upbound.io/v1beta1
              kind: API
              spec:
                forProvider:
                  region: eu-central-1
                  protocolType: WEBSOCKET
                  routeSelectionExpression: $request.body.action
                providerConfigRef:
                  name: aws-provider 
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-websocket-api-%s"
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.name
                transforms:
                  - type: string
                    string:
                      fmt: "user-admin-messaging-websocket-%s"
                      type: Format

          # S3 Bucket for User Interface
          - name: user-interface-bucket
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-user-interface-bucket-%s"
                      type: Format
          - name: lambda-package-bucket
            base:
              apiVersion: s3.aws.m.upbound.io/v1beta1
              kind: Bucket
              metadata:
                labels:
                  clc.lockhead.cloud/testing-aws-bucket: aws
                name: clc.lockhead.cloud.demo
              spec:
                forProvider:
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
          # CloudFront Distribution
          - name: cloudfront-distribution
            base:
              apiVersion: cloudfront.aws.m.upbound.io/v1beta1
              kind: Distribution
              spec:
                forProvider:
                  defaultRootObject: index.html
                  defaultCacheBehavior:
                    allowedMethods:
                      - DELETE
                      - GET
                      - HEAD
                      - OPTIONS
                      - PATCH
                      - POST
                      - PUT
                    cachedMethods:
                      - GET
                      - HEAD
                    defaultTtl: 3600
                    forwardedValues:
                      cookies:
                        forward: none
                      queryString: false
                    maxTtl: 86400
                    minTtl: 0
                    targetOriginId: customOrigin
                    viewerProtocolPolicy: allow-all
                  enabled: true
                  origin:
                  - customOriginConfig:
                      httpPort: 80
                      httpsPort: 443
                      originKeepaliveTimeout: 5
                      originProtocolPolicy: https-only
                      originReadTimeout: 10
                      originSslProtocols:
                        - TLSv1.2
                    domainName: lockhead.cloud
                    originId: customOrigin
                  viewerCertificate:
                    cloudfrontDefaultCertificate: true
                  restrictions:
                    geoRestriction:
                      locations:
                        - US
                        - CA
                        - GB
                        - DE
                      restrictionType: whitelist
                providerConfigRef:
                  name: aws-provider
                  kind: ProviderConfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "crossplane-cloudfront-distribution-%s"
                      type: Format
