// Configuration file for user interface
// Auto-generated by configure-endpoints script
// Generated on: 2025-10-29T21:49:39.858Z
// Environment: dev

import { FrontendConfigurationManager } from 'user-admin-messaging-shared-config';

export interface Config {
  environment: string;
  webSocketUrl: string;
  connectionType: 'user' | 'admin';
  reconnectInterval: number;
  maxReconnectAttempts: number;
  connectionTimeout: number;
  deploymentMode: string;
  enableLogging: boolean;
}

export const configManager = FrontendConfigurationManager.getInstance();

export const config: Config = {
  environment: 'dev',
  webSocketUrl: 'wss://lpoon64z0m.execute-api.eu-central-1.amazonaws.com/prod',
  connectionType: 'user',
  reconnectInterval: 5000,
  maxReconnectAttempts: 10,
  connectionTimeout: 30000,
  deploymentMode: 'aws',
  enableLogging: true
};
