# Production Environment Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-prod
  labels:
    app: user-admin-messaging
    component: config
    environment: production
data:
  # Redis configuration for production
  redis-url: "redis://redis-service:6379"
  redis-host: "redis-service"
  redis-port: "6379"
  
  # WebSocket configuration for production
  websocket-endpoint: "wss://clc.lockhead.cloud/ws"
  websocket-port: "8080"
  health-port: "8081"
  
  # Application configuration for production
  deployment-mode: "kubernetes"
  log-level: "warn"
  
  # Frontend configuration for production
  api-base-url: "https://clc.lockhead.cloud"
  websocket-reconnect-interval: "5000"
  websocket-max-retries: "5"
  
  # Performance configuration for production
  connection-timeout: "30000"
  message-timeout: "5000"
  max-connections-per-pod: "1000"
  
  # Environment-specific settings
  environment: "production"
  debug: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-prod
  labels:
    app: user-admin-messaging
    component: config
    environment: production
type: Opaque
data:
  # Production Redis password (base64 encoded)
  # IMPORTANT: Replace with actual secure production password
  redis-password: REPLACE_WITH_ACTUAL_PRODUCTION_PASSWORD
  
  # Production JWT secret (base64 encoded)
  # IMPORTANT: Replace with actual secure production JWT secret
  jwt-secret: REPLACE_WITH_ACTUAL_PRODUCTION_JWT_SECRET