apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
  labels:
    app: admin-frontend-service
    component: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: admin-frontend-service