apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - name: websocket
    port: 8080
    targetPort: websocket
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  selector:
    app: websocket-service